Andarist/react-textarea-autosize

src/TextareaAutosize.js

This check fixes server errors, where `window` is not defined.

Check if we're on server or not

---

src/TextareaAutosize.js

Under some circumstances, _resizeComponent can get called after the node is unmounted (because the action was scheduled via onNextFrame). This change attempts to remove all listeners when the element is unmounted which should prevent that error (see #30).
Sorry I don't have a way to test these changes as I'm travelling without my gear.

(Please review) Cancelling scheduled events

---

src/calculateNodeHeight.js

this broke for some browsers in 9b65e4d2, since they just return an empty string for border-top/border-bottom... sorry about that, should have tested the previous commit in more than just chrome :(

fix border-related calculations in some browsers

---

src/TextareaAutosize.js

This resolves an error we were seeing in our unit tests.
Two rapid prop changes followed by an unmount would cause
an error, since only the second would be cancelled.

clear next frame action before scheduling another

---

src/calculateNodeHeight.js

Using `text-rendering: optimizeLegibility` enables kerning and optional
ligatures, which may affect text metrics.
Here's an example of a pathological case of kerning:

Add text-rendering CSS property

---

src/calculateNodeHeight.js

If I remember correctly we did this change in Belle, because some IE versions the height will have scrollHeight of `0` in case the textarea has no value. I can double check this change tomorrow with a Windows computer.

fix(calculateNodeHeight): prevent return 0 for empty textareas

---

src/calculateNodeHeight.js

https://developer.mozilla.org/en-US/docs/Web/CSS/min-height
Here's an example of a site that has a global textarea style that sets min-height and ignores the invalid inlined min-height style.

'none' is not a valid value for min-height

---

.babelrc
.npmignore
package.json

The babel setup used by this package does not work with different setups. This PR tries to fix this by using the `.babelrc` file for local development and ignoring it for the npm package.

fix: removal of babel config from package.json

---

src/calculateNodeHeight.js

Unfortunately using `el.setAttribute("style", "...")` is blocked by our content security policy as it is considered "unsafe-inline" css.
This PR switches to direct property updates with `el.style[property] = value`, similar to how react itself handles changes to `style` on react elements.

Apply style attributes directly instead of setAttribute, to avoid CSP unsafe inline

---

src/TextareaAutosize.js

I found during performance testing that a not-insignificant amount of time was being spent going through the react lifecycle for this component. This is a simple optimization that avoids ever involving the lifecycle if the calculated height hasn't changed.

Only update state when values have changed

---

src/TextareaAutosize.js

I'm using react-textarea-autosize for server-side rendering and the default style.height value is 0.
This patch enables user to pass their own props.style.height values for initial height.

Set initial height to be any given props.style.height

---

.babelrc
Makefile
package.json
rollup.config.js

It looks like the build files assume that the consumer is using the CommonJS module format. I didn't see a UMD build, so this PR introduces one. I'm relying on Rollup to do the module bundling. 
Without the UMD build, using this module within ClojureScript wasn't really possible.

chore(*): Install rollup and build umd

---

README.md

I needed to set autofocus and had to look in the source for a way.
Perhaps it would be nice to also add a `autoFocus` prop that would set focus in `componentDidMount`. If you like this idea, I would prepare a PR.
Warm greetings!

docs: describe a way to set focus

---

README.md
src/calculateNodeHeight.js

**what is the change?:**
Make the hidden text area non-tabbable and hidden from screen readers.
**why make this change?:**
It violates some AA WCAG2 guidelines, as per this output from Pa11y:
```
{
"code": "WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Textarea.Name",
"context": "<textarea style=\"min-height: 0px !important; max-height: none !important; height: 0px !important; visibility: hidden !important; overflow: hidden !important; position: absolute !important; z-index: -1000 !important; top: 0px !important; right: 0px !i...",
"message": "This textarea element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.",
"type": "error",
"typeCode": 1,
"selector": "...(omitted)"
},
{
"code": …
```

Fix issue 251 add a11y ignore to hidden text area

---

.changeset/spotty-hornets-wait.md
src/index.tsx

We wrap this component at work, and wanna provide our own props based on the abse ones. Exporting it makes it easier to access (and matches what the package on DefinitelyTyped did)
(I made this edit in GH's UI, so a bit hard to add the changeset requested by the bot)

fix: export Props type

---

.changeset/rich-apes-argue.md
src/calculateNodeHeight.ts

Remove additional adding paddingSize and border because already contains in height (via getContentHeight)

Fix calculatation of height with box sizing 'border-box'

---

README.md

Since `inputRef` support has been deprecated with version `8`, I think it's time for the `README` to reflect it.
Regards

Updated ref attribute

---

.changeset/fuzzy-trains-sneeze.md
src/index.tsx

As discussed #276, this PR tries to add !important to inline property

fix: add `!important` to inline height property

---

.changeset/rude-squids-tickle.md
src/index.tsx

[IMPORTANT] fix: use string for `height` property

---

.changeset/fair-bobcats-matter.md
README.md
src/calculateNodeHeight.ts
src/index.tsx

feat: expose rowHeight from onHeightChange

---

.changeset/clean-kiwis-boil.md
src/hooks.ts
src/index.tsx

`useEffect` cleanup runs since React 17 asynchronously thats why it needs to be changed
We deployed this change to a web application with quite a lot of users and could verify that the `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.` errors were gone.
Fixes #259
cc @Andarist

fix: replace useEffect with useLayoutEffect for React 17

---

.changeset/purple-yaks-grin.md
package.json
src/index.tsx
yarn.lock

fixes https://github.com/Andarist/react-textarea-autosize/issues/310

Changed `TextareaAutosizeProps` to a TS interface

---

.changeset/quick-pianos-exercise.md
src/getSizingData.ts

This fixes #325 
* Include `'wordBreak'` in sizing style

Fix Height calculation is not accurate when using word-break

---

.changeset/rotten-radios-travel.md
src/calculateNodeHeight.ts

The "tab-index" property does not prevent the hidden element from being keyboard accessible, it should be tabindex. See https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

Change tab-index to tabindex.

---

.changeset/witty-garlics-pump.md
package.json
yarn.lock

* Adds support for the recently released [React 18](https://reactjs.org/blog/2022/03/29/react-v18.html).
* Updates NPM packages with newer versions that also support React 18.

Adds support for the recently released React 18.

---

.changeset/fair-pears-invite.md
.changeset/rotten-doors-fly.md
.changeset/rotten-doors-swim.md
package.json
src/getSizingData.ts
src/index.tsx
src/resolved-conditions/false.ts
src/resolved-conditions/true.ts
tsconfig.json
yarn.lock

closes https://github.com/Andarist/react-textarea-autosize/issues/372

Optimize bundling strategy

---

.changeset/great-moose-judge.md
src/hooks.ts

Sorry folks, only seeing the notifications now.
I made a simple change that should just safely handle `document.fonts` not being define.
Fixes #368

Handle document.fonts not being defined (IE9)

---

.changeset/two-turkeys-join.md
src/calculateNodeHeight.ts
src/forceHiddenStyles.ts

We had an issue where our product was embedded on customer sites. One customer set the display: none for all hidden textareas. This makes sure that the hidden textarea always has the `display: block` which is required for the resizing to work.

Prevent display style overrides from sites

---

.changeset/serious-shoes-draw.md
src/getSizingData.ts

Both options influence the sizing of the textarea and when you use a textarea where those two are not their initial values, sizing will be broken.

Add missing sizing styles wordSpacing & scrollbarGutter

---

.changeset/odd-donuts-approve.md
src/index.tsx

Can confirm this patch solved the issue in production for us, so this is the PR replicating it.
Fixes https://github.com/Andarist/react-textarea-autosize/issues/411

fix failed to execute getComputedStyle on window
