Andarist/react-textarea-autosize

- src/calculateNodeHeight.js
this fixes an issue where the height would always be a little too small if you have a border, resulting in perma-scrollbars in many browsers
incidentally this now also supports box-sizing:padding-box (firefox only)
> fix height calculation for box-sizing:border-box with a border

- example/index.js
- src/TextareaAutosize.js
> Invoke callback on height changes.

- package.json
This module is working fine on React 0.14 for me, I think this should be added as a dep
> Support all React 0.14 betas and alphas

- src/TextareaAutosize.js
fixes #43
:) thanks for the great component
> remove import to emptyFunction

- src/TextareaAutosize.js
Textarea component should automatically adjust its height when we resize browser window.
Changes:
- resizeComponent should listen to window resize events
> resizeComponent should listen to window resize events

- example/index.js
- src/calculateNodeHeight.js
> Use "" instead of "x" to calculate the height of empty textarea

- src/calculateNodeHeight.js
> Autoresize based on placeholder attribute

- src/calculateNodeHeight.js
@andreypopp any downsides I might have missed?
> improve height calculations to not be influenced by global css

- src/TextareaAutosize.js
I was little drunk yesterday while sending a pull request :D Here is a polished version.
> sugar for selection getter/setters

- src/TextareaAutosize.js
> Added inputRef prop.

- src/TextareaAutosize.js
> Unpack inputRef value

- .babelrc
- .gitignore
- Makefile
- package.json
- src/TextareaAutosize.js
> Added es modules build, more suitable for modern bundlers

- src/TextareaAutosize.js
Component is breaking is a test case where dom is not available.
> Check root dom node before computation

- example/index.js
- src/TextareaAutosize.js
- src/calculateNodeHeight.js
> Make rowCount available to onHeightChange callback

- README.md
Thanks for the [tip](https://github.com/andreypopp/react-textarea-autosize/pull/190) with autoFocus.
Perhaps it could be in docs too...
> docs: describe autoFocus

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/andreypopp/react-textarea-autosize/231)
> Use component name for import name in sample code

- src/index.tsx
I'm not used to this prettier configuration, sorry. 
I'd suggest to set up [Danger.js](https://danger.systems/js/) in PR to run some static checks like prettier.
> style: match `single-quote` prettier rule

- package.json
> Add engines in package.json

- .github/workflows/ci.yml
> devops: run GitHub Actions on incoming PRs

- .changeset/rich-garlics-film.md
- src/index.tsx
fixes https://github.com/Andarist/react-textarea-autosize/issues/376
> Always forward provided `onChange`

- .changeset/slimy-flowers-wink.md
- package.json
- yarn.lock
fixes https://github.com/Andarist/react-textarea-autosize/issues/379
> Publish files that were previously missing for some conditions

- .changeset/gentle-carrots-smoke.md
- package.json
- src/getSizingData.ts
- src/index.tsx
- src/resolved-conditions/browser.ts
- src/resolved-conditions/development.ts
- src/resolved-conditions/false.ts
- src/resolved-conditions/node.ts
- src/resolved-conditions/production.ts
- src/resolved-conditions/true.ts
- src/resolved-conditions/worker.ts
fixes https://github.com/Andarist/react-textarea-autosize/issues/385
> Distribute completely separate files for the `worker` condition
